greetTemplate: Hello, %s!
defaultName: Stranger
appContextPath: /api/*
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
logging:
  #
  #  # for performance on production left off.
  level: INFO